services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
      TZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  valkey:
    image: valkey/valkey:8-alpine
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data

  nats:
    image: nats:2.11-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "-js"
      - "-m"
      - "8222"
    volumes:
      - nats-data:/data

#  mailhog: #  For testing only
#    image: mailhog/mailhog:latest
#    ports:
#      - "8025:8025"
#      - "1025:1025"

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"

volumes:
  postgres-data:
  nats-data:
  valkey-data: